site_name: golang-jwt docs
site_url: https://golang-jwt.github.io/jwt/

repo_name: golang-jwt/jwt
repo_url: https://github.com/golang-jwt/jwt
edit_uri: ""

plugins:
  - social

theme:
  name: material
  palette:
    primary: light blue
    accent: purple
  logo: assets/jwt.png
  favicon: assets/jwt.png
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
